title: vislee
email: lazyvislee@gmail.com
description: > 
  保持一项爱好，让它在时间的深度和长度中慢慢生长，可能会得到始料未及的成就。
baseurl: ""
url: "https://vislee.github.io"
github_username: vislee

markdown: redcarpet

paginate: 8
